public class MainDriver {
    public static void main(String[] args) {
        GraphTraversal gt = new GraphTraversal();
        gt.addPlace("Labangon");
        gt.addPlace("Calamba");
        gt.addPlace("Sambag I");
        gt.addPlace("Sambag II");
        gt.addPlace("Kalubihan");
        gt.addPlace("Carbon Market");
        gt.addPlace("Magellan's Cross");
        gt.addPlace("Casa Gorordo Museum");
        gt.addPlace("Radisson Blu");
        gt.addPlace("Express Inn Mabolo");
        gt.addPlace("Hipodromo");
        gt.addPlace("Hostel 7");
        gt.addPlace("Ayala Center");
        gt.addPlace("Landers Superstore");
        gt.addPlace("Waterfront");
        gt.addPlace("Lahug");
        gt.addPlace("IT Park");
        gt.addPlace("Apas");
        gt.addPlace("Banilad");
        gt.addPlace("Kasambagan");

        gt.connect("Labangon", "Calamba",1.0);
        gt.connect("Labangon", "Sambag I",2.0);
        gt.connect("Sambag I", "Sambag II",1.2);
        gt.connect("Sambag I", "Kalubihan",1.0);
        gt.connect("Sambag I", "Hostel 7",2.2);
        gt.connect("Sambag II", "Calamba",1.7);
        gt.connect("Sambag II", "Lahug",4.9);
        gt.connect("Kalubihan", "Carbon Market",0.65);
        gt.connect("Kalubihan", "Hipodromo",2.9);
        gt.connect("Carbon Market", "Magellan's Cross",0.4);
        gt.connect("Magellan's Cross", "Casa Gorordo Museum",0.9);
        gt.connect("Hipodromo", "Hostel 7",2.2);
        gt.connect("Hipodromo", "Ayala Center",1.3);
        gt.connect("Hipodromo", "Express Inn Mabolo",1.0);
        gt.connect("Hipodromo", "Casa Gorordo Museum",1.9);
        gt.connect("Casa Gorordo Museum", "Radisson Blu",3.0);
        gt.connect("Radisson Blu", "Express Inn Mabolo",0.8);
        gt.connect("Express Inn Mabolo", "Landers Superstore",1.7);
        gt.connect("Hostel 7", "Ayala Center",1.7);
        gt.connect("Ayala Center", "Landers Superstore",0.5);
        gt.connect("Landers Superstore", "Waterfront",1.1);
        gt.connect("Lahug", "Waterfront",2.2);
        gt.connect("Waterfront", "IT Park",1.1);
        gt.connect("IT Park", "Apas",1.9);
        gt.connect("Apas", "Banilad",2.4);
        gt.connect("Banilad", "Kasambagan",5.0);

        System.out.println("Adjacency List\n--------------");
        gt.displayAdjacencyList();
        System.out.println();
        System.out.println("BFS\n---");
        gt.breadthFirstSearch("Labangon","Lahug");
        System.out.println();
        System.out.println("DFS\n---");
        gt.depthFirstSearch("Labangon","Lahug");
        System.out.println();
        System.out.println("DFS Recursive\n-------------");
        gt.depthFirstSearchRecursive("Labangon","Lahug");
        System.out.println();
        System.out.println("GBFS\n----");
        gt.greedyBestFirstSearch("Labangon","Lahug");
        System.out.println();
        System.out.println("A*\n--");
        gt.aStarSearch("Labangon","Lahug");
    }
}